// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: pkg/proto/federated_learning.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederatedLearning_SendModelUpdate_FullMethodName = "/proto.FederatedLearning/SendModelUpdate"
	FederatedLearning_GetGlobalModel_FullMethodName  = "/proto.FederatedLearning/GetGlobalModel"
)

// FederatedLearningClient is the client API for FederatedLearning service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FederatedLearning service defines the RPC methods for federated learning.
type FederatedLearningClient interface {
	// Clients send their local model updates to the server.
	SendModelUpdate(ctx context.Context, in *ModelUpdate, opts ...grpc.CallOption) (*Acknowledgement, error)
	// Clients request the current global model from the server.
	GetGlobalModel(ctx context.Context, in *GlobalModelRequest, opts ...grpc.CallOption) (*GlobalModel, error)
}

type federatedLearningClient struct {
	cc grpc.ClientConnInterface
}

func NewFederatedLearningClient(cc grpc.ClientConnInterface) FederatedLearningClient {
	return &federatedLearningClient{cc}
}

func (c *federatedLearningClient) SendModelUpdate(ctx context.Context, in *ModelUpdate, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, FederatedLearning_SendModelUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedLearningClient) GetGlobalModel(ctx context.Context, in *GlobalModelRequest, opts ...grpc.CallOption) (*GlobalModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalModel)
	err := c.cc.Invoke(ctx, FederatedLearning_GetGlobalModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederatedLearningServer is the server API for FederatedLearning service.
// All implementations must embed UnimplementedFederatedLearningServer
// for forward compatibility.
//
// FederatedLearning service defines the RPC methods for federated learning.
type FederatedLearningServer interface {
	// Clients send their local model updates to the server.
	SendModelUpdate(context.Context, *ModelUpdate) (*Acknowledgement, error)
	// Clients request the current global model from the server.
	GetGlobalModel(context.Context, *GlobalModelRequest) (*GlobalModel, error)
	mustEmbedUnimplementedFederatedLearningServer()
}

// UnimplementedFederatedLearningServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederatedLearningServer struct{}

func (UnimplementedFederatedLearningServer) SendModelUpdate(context.Context, *ModelUpdate) (*Acknowledgement, error) {
	return nil, status.Error(codes.Unimplemented, "method SendModelUpdate not implemented")
}
func (UnimplementedFederatedLearningServer) GetGlobalModel(context.Context, *GlobalModelRequest) (*GlobalModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalModel not implemented")
}
func (UnimplementedFederatedLearningServer) mustEmbedUnimplementedFederatedLearningServer() {}
func (UnimplementedFederatedLearningServer) testEmbeddedByValue()                           {}

// UnsafeFederatedLearningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederatedLearningServer will
// result in compilation errors.
type UnsafeFederatedLearningServer interface {
	mustEmbedUnimplementedFederatedLearningServer()
}

func RegisterFederatedLearningServer(s grpc.ServiceRegistrar, srv FederatedLearningServer) {
	// If the following call panics, it indicates UnimplementedFederatedLearningServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederatedLearning_ServiceDesc, srv)
}

func _FederatedLearning_SendModelUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLearningServer).SendModelUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederatedLearning_SendModelUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLearningServer).SendModelUpdate(ctx, req.(*ModelUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedLearning_GetGlobalModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLearningServer).GetGlobalModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederatedLearning_GetGlobalModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLearningServer).GetGlobalModel(ctx, req.(*GlobalModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FederatedLearning_ServiceDesc is the grpc.ServiceDesc for FederatedLearning service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederatedLearning_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FederatedLearning",
	HandlerType: (*FederatedLearningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendModelUpdate",
			Handler:    _FederatedLearning_SendModelUpdate_Handler,
		},
		{
			MethodName: "GetGlobalModel",
			Handler:    _FederatedLearning_GetGlobalModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/federated_learning.proto",
}
