// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pkg/proto/federated_learning.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModelUpdate represents a client's local model update.
type ModelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Weights       map[string]float32     `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Metrics       map[string]float32     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelUpdate) Reset() {
	*x = ModelUpdate{}
	mi := &file_pkg_proto_federated_learning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdate) ProtoMessage() {}

func (x *ModelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federated_learning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdate.ProtoReflect.Descriptor instead.
func (*ModelUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federated_learning_proto_rawDescGZIP(), []int{0}
}

func (x *ModelUpdate) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ModelUpdate) GetWeights() map[string]float32 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *ModelUpdate) GetMetrics() map[string]float32 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GlobalModelRequest is sent by a client to request the current global model.
type GlobalModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalModelRequest) Reset() {
	*x = GlobalModelRequest{}
	mi := &file_pkg_proto_federated_learning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalModelRequest) ProtoMessage() {}

func (x *GlobalModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federated_learning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalModelRequest.ProtoReflect.Descriptor instead.
func (*GlobalModelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federated_learning_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalModelRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// GlobalModel contains the aggregated global model parameters.
type GlobalModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weights       map[string]float32     `protobuf:"bytes,1,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalModel) Reset() {
	*x = GlobalModel{}
	mi := &file_pkg_proto_federated_learning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalModel) ProtoMessage() {}

func (x *GlobalModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federated_learning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalModel.ProtoReflect.Descriptor instead.
func (*GlobalModel) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federated_learning_proto_rawDescGZIP(), []int{2}
}

func (x *GlobalModel) GetWeights() map[string]float32 {
	if x != nil {
		return x.Weights
	}
	return nil
}

// Acknowledgement is a simple response from the server.
type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_pkg_proto_federated_learning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federated_learning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federated_learning_proto_rawDescGZIP(), []int{3}
}

func (x *Acknowledgement) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_federated_learning_proto protoreflect.FileDescriptor

const file_pkg_proto_federated_learning_proto_rawDesc = "" +
	"\n" +
	"\"pkg/proto/federated_learning.proto\x12\x05proto\"\x98\x02\n" +
	"\vModelUpdate\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x129\n" +
	"\aweights\x18\x02 \x03(\v2\x1f.proto.ModelUpdate.WeightsEntryR\aweights\x129\n" +
	"\ametrics\x18\x03 \x03(\v2\x1f.proto.ModelUpdate.MetricsEntryR\ametrics\x1a:\n" +
	"\fWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"1\n" +
	"\x12GlobalModelRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x84\x01\n" +
	"\vGlobalModel\x129\n" +
	"\aweights\x18\x01 \x03(\v2\x1f.proto.GlobalModel.WeightsEntryR\aweights\x1a:\n" +
	"\fWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"+\n" +
	"\x0fAcknowledgement\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x93\x01\n" +
	"\x11FederatedLearning\x12=\n" +
	"\x0fSendModelUpdate\x12\x12.proto.ModelUpdate\x1a\x16.proto.Acknowledgement\x12?\n" +
	"\x0eGetGlobalModel\x12\x19.proto.GlobalModelRequest\x1a\x12.proto.GlobalModelB9Z7github.com/Poin1961/federated-learning-system/pkg/protob\x06proto3"

var (
	file_pkg_proto_federated_learning_proto_rawDescOnce sync.Once
	file_pkg_proto_federated_learning_proto_rawDescData []byte
)

func file_pkg_proto_federated_learning_proto_rawDescGZIP() []byte {
	file_pkg_proto_federated_learning_proto_rawDescOnce.Do(func() {
		file_pkg_proto_federated_learning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_federated_learning_proto_rawDesc), len(file_pkg_proto_federated_learning_proto_rawDesc)))
	})
	return file_pkg_proto_federated_learning_proto_rawDescData
}

var file_pkg_proto_federated_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_federated_learning_proto_goTypes = []any{
	(*ModelUpdate)(nil),        // 0: proto.ModelUpdate
	(*GlobalModelRequest)(nil), // 1: proto.GlobalModelRequest
	(*GlobalModel)(nil),        // 2: proto.GlobalModel
	(*Acknowledgement)(nil),    // 3: proto.Acknowledgement
	nil,                        // 4: proto.ModelUpdate.WeightsEntry
	nil,                        // 5: proto.ModelUpdate.MetricsEntry
	nil,                        // 6: proto.GlobalModel.WeightsEntry
}
var file_pkg_proto_federated_learning_proto_depIdxs = []int32{
	4, // 0: proto.ModelUpdate.weights:type_name -> proto.ModelUpdate.WeightsEntry
	5, // 1: proto.ModelUpdate.metrics:type_name -> proto.ModelUpdate.MetricsEntry
	6, // 2: proto.GlobalModel.weights:type_name -> proto.GlobalModel.WeightsEntry
	0, // 3: proto.FederatedLearning.SendModelUpdate:input_type -> proto.ModelUpdate
	1, // 4: proto.FederatedLearning.GetGlobalModel:input_type -> proto.GlobalModelRequest
	3, // 5: proto.FederatedLearning.SendModelUpdate:output_type -> proto.Acknowledgement
	2, // 6: proto.FederatedLearning.GetGlobalModel:output_type -> proto.GlobalModel
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_federated_learning_proto_init() }
func file_pkg_proto_federated_learning_proto_init() {
	if File_pkg_proto_federated_learning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_federated_learning_proto_rawDesc), len(file_pkg_proto_federated_learning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_federated_learning_proto_goTypes,
		DependencyIndexes: file_pkg_proto_federated_learning_proto_depIdxs,
		MessageInfos:      file_pkg_proto_federated_learning_proto_msgTypes,
	}.Build()
	File_pkg_proto_federated_learning_proto = out.File
	file_pkg_proto_federated_learning_proto_goTypes = nil
	file_pkg_proto_federated_learning_proto_depIdxs = nil
}
